#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not handle the case statement correctly, edit this file and add the missing
#       case statements for your system. Problem reported to Cygwin.
#   (2) The Java JDK is installed and JAVA_HOME is set to one of:
#       /usr/java/default
#       /usr/bin/java
#       /usr/bin/jre
#       /Library/Java/Home
#       /usr/java
#       /usr/local/java
#       /usr/local/java/bin
#       /opt/java
#   (3) You need to set JAVA_HOME before running this script,
#       or edit this file and set JAVA_HOME to the Java home directory.
#   (4) When running Cygwin, use the Windows native javaw command
#       instead of a Unix emulator (returns a Windows exit code).
#
##############################################################################

if [ -z "$JAVA_HOME" ] ; then
    java_cmd=java
else
    java_cmd="$JAVA_HOME/bin/java"
fi

if ! command -v $java_cmd >/dev/null 2>&1; then
    >&2 echo "Java is required to run this script ($java_cmd)."
    >&2 echo "Please set the JAVA_HOME variable in your environment to match the"
    >&2 echo "location of your Java installation."
    exit 1
fi

set -- "$@" "-Dorg.gradle.appname=$APP_BASE_NAME"

exec "$java_cmd" \
    -cp gradle/wrapper/gradle-wrapper.jar \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
